# coding: utf-8

"""
    User exchange API

    User exchange API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: prokhorov.va@phystech.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Init(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'input_number': 'int',
        'config_location': 'str'
    }

    attribute_map = {
        'input_number': 'inputNumber',
        'config_location': 'configLocation'
    }

    def __init__(self, input_number=None, config_location=None):  # noqa: E501
        """Init - a model defined in Swagger"""  # noqa: E501
        self._input_number = None
        self._config_location = None
        self.discriminator = None
        if input_number is not None:
            self.input_number = input_number
        if config_location is not None:
            self.config_location = config_location

    @property
    def input_number(self):
        """Gets the input_number of this Init.  # noqa: E501


        :return: The input_number of this Init.  # noqa: E501
        :rtype: int
        """
        return self._input_number

    @input_number.setter
    def input_number(self, input_number):
        """Sets the input_number of this Init.


        :param input_number: The input_number of this Init.  # noqa: E501
        :type: int
        """

        self._input_number = input_number

    @property
    def config_location(self):
        """Gets the config_location of this Init.  # noqa: E501


        :return: The config_location of this Init.  # noqa: E501
        :rtype: str
        """
        return self._config_location

    @config_location.setter
    def config_location(self, config_location):
        """Sets the config_location of this Init.


        :param config_location: The config_location of this Init.  # noqa: E501
        :type: str
        """

        self._config_location = config_location

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Init, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Init):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
