# coding: utf-8

"""
    Preprocessor server

    This is a simple API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: mipt@mipt.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.nums import Nums  # noqa: E501
from swagger_client.rest import ApiException


class TestNums(unittest.TestCase):
    """Nums unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNums(self):
        """Test Nums"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.nums.Nums()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
