# coding: utf-8

"""
    Preprocessor server

    This is a simple API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: mipt@mipt.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.api_api import ApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestApiApi(unittest.TestCase):
    """ApiApi unit test stubs"""

    def setUp(self):
        self.api = ApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_results(self):
        """Test case for get_results

        Get previous results  # noqa: E501
        """
        pass

    def test_operate(self):
        """Test case for operate

        operate 2 numbers  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
