# coding: utf-8

"""
    Preprocessor API

    This is MIPT-2PC preprocessor API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: prokhorov.va@phystech.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client_pre
from swagger_client_pre.models.table import Table  # noqa: E501
from swagger_client_pre.rest import ApiException


class TestTable(unittest.TestCase):
    """Table unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTable(self):
        """Test Table"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.table.Table()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
