# coding: utf-8

"""
    Preprocessor API

    This is MIPT-2PC preprocessor API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: mipt@mipt.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.interaction_api import InteractionApi  # noqa: E501
from swagger_client.rest import ApiException


class TestInteractionApi(unittest.TestCase):
    """InteractionApi unit test stubs"""

    def setUp(self):
        self.api = InteractionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_table(self):
        """Test case for get_table

        hello message to get preprocessed data  # noqa: E501
        """
        pass

    def test_start2_pc(self):
        """Test case for start2_pc

        start preprocessing procedure  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
