<<<<<<< Updated upstream:client-side/swagger_client/models/__init__.py
=======
# coding: utf-8

# flake8: noqa
"""
    User exchange API

    User exchange API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: prokhorov.va@phystech.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client_pre.models.answer import Answer
from swagger_client_pre.models.exchange_payload import ExchangePayload
from swagger_client_pre.models.init import Init
from swagger_client_pre.models.inline_response200 import InlineResponse200
from swagger_client_pre.models.table import Table
>>>>>>> Stashed changes:client-side/swagger_client_pre/models/__init__.py
