# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ExchangePayload(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, start_index: int=None, filled_links: object=None, end_index: int=None):  # noqa: E501
        """ExchangePayload - a model defined in Swagger

        :param start_index: The start_index of this ExchangePayload.  # noqa: E501
        :type start_index: int
        :param filled_links: The filled_links of this ExchangePayload.  # noqa: E501
        :type filled_links: object
        :param end_index: The end_index of this ExchangePayload.  # noqa: E501
        :type end_index: int
        """
        self.swagger_types = {
            'start_index': int,
            'filled_links': object,
            'end_index': int
        }

        self.attribute_map = {
            'start_index': 'startIndex',
            'filled_links': 'filledLinks',
            'end_index': 'endIndex'
        }
        self._start_index = start_index
        self._filled_links = filled_links
        self._end_index = end_index

    @classmethod
    def from_dict(cls, dikt) -> 'ExchangePayload':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ExchangePayload of this ExchangePayload.  # noqa: E501
        :rtype: ExchangePayload
        """
        return util.deserialize_model(dikt, cls)

    @property
    def start_index(self) -> int:
        """Gets the start_index of this ExchangePayload.


        :return: The start_index of this ExchangePayload.
        :rtype: int
        """
        return self._start_index

    @start_index.setter
    def start_index(self, start_index: int):
        """Sets the start_index of this ExchangePayload.


        :param start_index: The start_index of this ExchangePayload.
        :type start_index: int
        """

        self._start_index = start_index

    @property
    def filled_links(self) -> object:
        """Gets the filled_links of this ExchangePayload.


        :return: The filled_links of this ExchangePayload.
        :rtype: object
        """
        return self._filled_links

    @filled_links.setter
    def filled_links(self, filled_links: object):
        """Sets the filled_links of this ExchangePayload.


        :param filled_links: The filled_links of this ExchangePayload.
        :type filled_links: object
        """

        self._filled_links = filled_links

    @property
    def end_index(self) -> int:
        """Gets the end_index of this ExchangePayload.


        :return: The end_index of this ExchangePayload.
        :rtype: int
        """
        return self._end_index

    @end_index.setter
    def end_index(self, end_index: int):
        """Sets the end_index of this ExchangePayload.


        :param end_index: The end_index of this ExchangePayload.
        :type end_index: int
        """

        self._end_index = end_index
