# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Init(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, input_number: int=None, config: str=None):  # noqa: E501
        """Init - a model defined in Swagger

        :param input_number: The input_number of this Init.  # noqa: E501
        :type input_number: int
        :param config: The config of this Init.  # noqa: E501
        :type config: str
        """
        self.swagger_types = {
            'input_number': int,
            'config': str
        }

        self.attribute_map = {
            'input_number': 'inputNumber',
            'config': 'config'
        }
        self._input_number = input_number
        self._config = config

    @classmethod
    def from_dict(cls, dikt) -> 'Init':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Init of this Init.  # noqa: E501
        :rtype: Init
        """
        return util.deserialize_model(dikt, cls)

    @property
    def input_number(self) -> int:
        """Gets the input_number of this Init.


        :return: The input_number of this Init.
        :rtype: int
        """
        return self._input_number

    @input_number.setter
    def input_number(self, input_number: int):
        """Sets the input_number of this Init.


        :param input_number: The input_number of this Init.
        :type input_number: int
        """

        self._input_number = input_number

    @property
    def config(self) -> str:
        """Gets the config of this Init.


        :return: The config of this Init.
        :rtype: str
        """
        return self._config

    @config.setter
    def config(self, config: str):
        """Sets the config of this Init.


        :param config: The config of this Init.
        :type config: str
        """

        self._config = config
