# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Init(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, input_number: int=None, config_location: str=None):  # noqa: E501
        """Init - a model defined in Swagger

        :param input_number: The input_number of this Init.  # noqa: E501
        :type input_number: int
        :param config_location: The config_location of this Init.  # noqa: E501
        :type config_location: str
        """
        self.swagger_types = {
            'input_number': int,
            'config_location': str
        }

        self.attribute_map = {
            'input_number': 'inputNumber',
            'config_location': 'configLocation'
        }
        self._input_number = input_number
        self._config_location = config_location

    @classmethod
    def from_dict(cls, dikt) -> 'Init':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Init of this Init.  # noqa: E501
        :rtype: Init
        """
        return util.deserialize_model(dikt, cls)

    @property
    def input_number(self) -> int:
        """Gets the input_number of this Init.


        :return: The input_number of this Init.
        :rtype: int
        """
        return self._input_number

    @input_number.setter
    def input_number(self, input_number: int):
        """Sets the input_number of this Init.


        :param input_number: The input_number of this Init.
        :type input_number: int
        """

        self._input_number = input_number

    @property
    def config_location(self) -> str:
        """Gets the config_location of this Init.


        :return: The config_location of this Init.
        :rtype: str
        """
        return self._config_location

    @config_location.setter
    def config_location(self, config_location: str):
        """Sets the config_location of this Init.


        :param config_location: The config_location of this Init.
        :type config_location: str
        """

        self._config_location = config_location
