# coding: utf-8

"""
    User exchange API

    User exchange API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: mipt@mipt.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.interaction_api import InteractionApi  # noqa: E501
from swagger_client.rest import ApiException


class TestInteractionApi(unittest.TestCase):
    """InteractionApi unit test stubs"""

    def setUp(self):
        self.api = InteractionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_exchange_out(self):
        """Test case for exchange_out

        Exchange calculated nodes with self table from Nth layer  # noqa: E501
        """
        pass

    def test_hello(self):
        """Test case for hello

        hello message to get preprocessed data  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
