# coding: utf-8

"""
    User exchange API

    User exchange API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: prokhorov.va@phystech.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client_pre
from swagger_client_pre.api.external_calls_api import ExternalCallsApi  # noqa: E501
from swagger_client_pre.rest import ApiException


class TestExternalCallsApi(unittest.TestCase):
    """ExternalCallsApi unit test stubs"""

    def setUp(self):
        self.api = ExternalCallsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_result(self):
        """Test case for get_result

        returns calculated with 2PC result  # noqa: E501
        """
        pass

    def test_init(self):
        """Test case for init

        Init call to start 2PC process.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
