# coding: utf-8

# flake8: noqa
"""
    Preprocessor server

    This is a simple API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: mipt@mipt.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.nums import Nums
from swagger_client.models.results import Results
