# coding: utf-8

# flake8: noqa
"""
    Preprocessor API

    This is MIPT-2PC preprocessor API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: prokhorov.va@phystech.edu
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
<<<<<<< HEAD:client-of-preprocessor/swagger_client_pre/models/__init__.py
from swagger_client_pre.models.table import Table
=======
from swagger_client.models.table import Table
>>>>>>> dc234be97aeebc8f19b6f397789ae22d154cd876:client-of-preprocessor/swagger_client/models/__init__.py
