name: Swagger code generator

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  generate:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@main
    - name: save_controllers
      run: cp server-side/swagger_server/controllers/*_controller.py . # save our implementation for later use
    - name: Swagger Codegen v3
      uses: ducksify/swagger-codegen-action@v3.0
      with:
        args: >
          generate
          -i server-side/swagger_server/swagger/swagger.yaml
          -l python-flask
          -o server-side
    - name: restore controllers
      run: |
        echo saving generated controllers to controllers_new
        for filename in server-side/swagger_server/controllers/*_controller.py; # renaming file
        do
        mv "$filename" "$(echo "$filename" | sed s/_controller.py/_controller_template.py/)";
        done
        echo restoring controllers
        cp *_controller.py server-side/swagger_server/controllers/
        rm *_controller.py
        echo replacing dateutil version
        sed -i 's/python_dateutil == 2.6.0/python_dateutil == 2.7.0/' server-side/requirements.txt # replace dateutil version. Error with UTP on 2.6.0
        sed -i 's/flask_testing==0.8.0/flask_testing==0.8.1/' server-side/test-requirements.txt
        sed -i 's/envlist = py35/envlist = py36/' server-side/tox.ini
    - name: rename client-of-preprocessor module
      run: |
        if [ -d ./client-of-preprocessor/swagger_client_pre ]; then
          mv ./client-of-preprocessor/swagger_client_pre ./client-of-preprocessor/swagger_client_pre
        fi
        find ./client-of-preprocessor/swagger_client_pre \( -type d -name .git -prune \) -o -type f -print0 | xargs -0 sed -i 's/swagger\_client/swagger_client_pre/g'
    - name: patch __main__.py
      if: always()
      run: |
        echo "patching __main__.py"
        patch server-side/swagger_server/__main__.py < server-side/__main__.patch
    - name: patch configuration.py
      if: always()
      run: |
        echo "patching configuration.py"
        patch client-side/swagger_server/configuration.py < client-side/__configuration__.patch
    - uses: stefanzweifel/git-auto-commit-action@v4 # commiting changes